name: Los Shells
on:
    push:
        branches:
            ["main"]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Bash
              shell: bash
              run : echo $0
            - name : sh
              shell: sh
              run: echo $0
            - name: Default
              run: echo $0
